### ISSUE TITLE
Informações sobre a biblioteca

### ISSUE THREAD

**Issue by 11JoseMarcos11** [iShareLife/braspag#2]
Bom dia, Carneiro. Tudo bem?

A sua biblioteca tem mais de 5 anos. Ela ainda é válida se usarmos hoje (2021) em nossas aplicações? Pois de todas que procuramos, a sua parece ser a mais fácil de usar.

Obrigado!

**Comment by carneiro** [comment]
Olá! Utilizamos esse projeto por dois anos após a abertura de código no github. Depois migramos de fornecedor e pela falta de interesse no pacote resolvemos não manter mais. Melhor caminho seria baixar e tentar rodar numa sandbox para ver as possíveis exceções batendo com o manual da braspag. Se tiver interesse em manter o código após possíveis adaptações fala comigo que te coloco como colaborador.
